### ISSUE TITLE
Updating and deleting records not working

### ISSUE THREAD

**Issue by benpoliquin** [rbw0/pysnow#68]
I am using this library to build a quick CRUD app and am unable to update/delete a record. 

I am able to connect and get single/multiple records. When I update/delete it does nothing and then returns the original record. I am using your examples as well.

Example tables I have tried incident, problem, and cmdb_ci_server. None work. Any Ideas?

Using a dev instance from https://developer.servicenow.com/ on version Jakarta. Tried with python2.8 & python3.6

**Comment by rbw0** [comment]
Hello!

I just tested creating, updating and deleting an incident and it works fine with the latest stable version (0.5.2). Also, all tests pass with full coverage.

You could try the current development branch (0.6), I've reworked the query-request-response flow there, but I don't think the issue is with pysnow tbh.

Could this be due to some access restriction in your ServiceNow instance?

**Comment by benpoliquin** [comment]
Weird. I will try the dev branch. I dont think its an access restriction because I'm using an admin account and have been able to create/edit via REST POST. I'll close this out though. Thank you for the quick response!

**Comment by rbw0** [comment]
OK. The documentation is available here:
http://pysnow.readthedocs.io/en/branch-0.6.0
